---
Name: ecommerce_also_bought
Before:
  - '#app'
After:
  - '#coreconfig'
  - '#cmsextensions'
  - '#ecommerce'
---
Sunnysideup\Ecommerce\Pages\Product:
  extensions:
    - Sunnysideup\EcommerceAlsoBought\Model\EcommerceAlsoBoughtDOD
